name: release

on:
  release:
    types: [ created ]

permissions:
  contents: write

env:
  CGO_ENABLED: '0'
  GO386: sse2

jobs:
  create-release:
    name: Release mnemonikey Binary
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ "386", amd64, arm64 ]
        exclude:
          - goarch: "386"
            goos: darwin

    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@b98909985b9c1fd7b0aaa4c51257a7ba49995781
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goamd64: v1
          goversion: "https://dl.google.com/go/go1.20.7.linux-amd64.tar.gz"
          project_path: "./cmd/mnemonikey"
          asset_name: "mnemonikey-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          extra_files: LICENSE README.md
          build_flags: "-trimpath -buildvcs=false"
          ldflags: "-s -w"
          md5sum: FALSE
